# Generated by Django 4.2.24 on 2025-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_alter_position_avg_sell_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="avg_buy_price",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name="position",
            name="avg_sell_price",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="quantity",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name="position",
            name="quantity_usdt",
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
