# Generated by Django 4.2.24 on 2025-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_alter_position_avg_buy_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
